#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 21, 2022 09:46:44 PM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import threading

import guiprograma_support

class Toplevel1:
    def __init__(self, top=None):
        self.dic_algoritmos={
        'bubblesort':0,
        'bucketsort':1,
        'countingsort':2,
        'heapsort':3,
        'quicksort':4,
        'mergesort':5,
        'insertionsort':6,
        'shellsort':7,
        'stoogesort':8,
        'selectionsort':9,
        'radixsort':10,
        'Todos':11
         }

        def iniciar(a,b,c,d,e,f,g,h,i,j):
            threading.Thread(name="gui", target=guiprograma_support.iniciar,args=(a,b,c,d,e,f,g,h,i,j)).start()

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("752x762+418+24")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Algoritmos De Ordenamiento")
        top.configure(background="#EEEDDE")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.configure(cursor="hand2")
        algoritmos=('bubblesort','bucketsort','countingsort','heapsort','quicksort','mergesort','insertionsort','shellsort','stoogesort','selectionsort','radixsort','Todos')
        letras=["letras","numeros"]

        self.top = top
        self.combobox = tk.StringVar()

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=-0.013, height=100, width=757)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="#7b6bd6")
        self.Label1.configure(background="#203239")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arial} -size 18 -slant italic")
        self.Label1.configure(foreground="#EEEDDE")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Algoritmos de Ordenamiento-Erick Meza y Ronald Meza''')


        self.TCombobox1 = ttk.Combobox(self.top,values=algoritmos)
        self.TCombobox1.place(relx=0.146, rely=0.157, relheight=0.029
                , relwidth=0.149)
        self.TCombobox1.configure(textvariable=self.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.04, rely=0.157, height=26, width=72)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#EEEDDE")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Algoritmos:''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.04, rely=0.197, height=28, width=57)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#EEEDDE")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Entrada:''')
        self.entrada = tk.StringVar()
        self.TCombobox2 = ttk.Combobox(self.top,values=letras)
        self.TCombobox2.place(relx=0.146, rely=0.197, relheight=0.029
                , relwidth=0.15)

                
        self.TCombobox2.configure(textvariable=self.entrada)
        self.TCombobox2.configure(takefocus="")

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.04, rely=0.236, height=18, width=48)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#EEEDDE")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Digitos:''')

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.146, rely=0.236, relheight=0.028, relwidth=0.136)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.insert("1.0","0")
        self.Text1.configure(wrap="word")

        self.Listbox1 = tk.Listbox(self.top)
        
        self.Listbox1.place(relx=0.306, rely=0.184, relheight=0.344
                , relwidth=0.251)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

        self.Listbox2 = tk.Listbox(self.top)
        self.Listbox2.place(relx=0.598, rely=0.184, relheight=0.344
                , relwidth=0.291)
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(disabledforeground="#a3a3a3")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(foreground="#000000")

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.035, rely=0.274, height=17, width=52)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#EEEDDE")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Cantidad:''')


        self.Text2 = tk.Text(self.top)
        self.Text2.place(relx=0.146, rely=0.276, relheight=0.026, relwidth=0.137)

        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="blue")
        self.Text2.configure(selectforeground="white")
        self.Text2.configure(wrap="word")

        self.Button1 = tk.Button(self.top,command=lambda:iniciar(self.dic_algoritmos[self.TCombobox1.get()], self.TCombobox2.get(),
                                                                 self.Text1.get("1.0","end"),self.Text2.get("1.0","end"),
                                                                 self.Text3.get("1.0","end"),self.Text4.get("1.0","end"),self.Listbox1,self.Listbox2,
                                                                 self.Listbox3,self.Listbox4))
        self.Button1.place(relx=0.04, rely=0.394, height=34, width=137)
        self.Button1.configure(activebackground="#EEEDDE")
        self.Button1.configure(activeforeground="#EEEDDE")
        self.Button1.configure(background="#203239")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#EEEDDE")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Iniciar''')

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.035, rely=0.314, height=19, width=52)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#EEEDDE")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Epocas''')

        self.Label7 = tk.Label(self.top)
        self.Label7.place(relx=0.035, rely=0.349, height=18, width=32)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#EEEDDE")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Saltos''')

        self.Text3 = tk.Text(self.top)
        self.Text3.place(relx=0.146, rely=0.315, relheight=0.029, relwidth=0.136)

        self.Text3.configure(background="white")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="blue")
        self.Text3.configure(selectforeground="white")
        self.Text3.configure(wrap="word")

        self.Text4 = tk.Text(self.top)
        self.Text4.place(relx=0.146, rely=0.354, relheight=0.029, relwidth=0.137)

        self.Text4.configure(background="white")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="#d9d9d9")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="blue")
        self.Text4.configure(selectforeground="white")
        self.Text4.configure(wrap="word")
        self.entrada.trace('w',lambda name, index, mode : guiprograma_support.entrada(self.Text1,self.TCombobox2.get()))


        self.Label8 = tk.Label(self.top)
        self.Label8.place(relx=0.309, rely=0.157, height=19, width=144)
        self.Label8.configure(activebackground="#EEEDDE")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#EEEDDE")
        self.Label8.configure(compound='left')
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Cantidad - Algoritmo''')

        self.Label9 = tk.Label(self.top)
        self.Label9.place(relx=0.598, rely=0.157, height=19, width=170)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(anchor='w')
        self.Label9.configure(background="#EEEDDE")
        self.Label9.configure(compound='left')
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Tiempo''')

        self.Listbox3 = tk.Listbox(self.top)
        self.Listbox3.place(relx=0.306, rely=0.604, relheight=0.34
                , relwidth=0.25)
        self.Listbox3.configure(background="white")
        self.Listbox3.configure(cursor="fleur")
        self.Listbox3.configure(disabledforeground="#a3a3a3")
        self.Listbox3.configure(font="TkFixedFont")
        self.Listbox3.configure(foreground="#000000")
        self.Listbox3.configure(highlightbackground="#d9d9d9")
        self.Listbox3.configure(highlightcolor="black")
        self.Listbox3.configure(selectbackground="blue")
        self.Listbox3.configure(selectforeground="white")

        self.Label10 = tk.Label(self.top)
        self.Label10.place(relx=0.306, rely=0.577, height=19, width=148)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(anchor='w')
        self.Label10.configure(background="#EEEDDE")
        self.Label10.configure(compound='left')
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Lista Random''')

        self.Listbox4 = tk.Listbox(self.top)
        self.Listbox4.place(relx=0.598, rely=0.604, relheight=0.34
                , relwidth=0.293)
        self.Listbox4.configure(background="white")
        self.Listbox4.configure(disabledforeground="#a3a3a3")
        self.Listbox4.configure(font="TkFixedFont")
        self.Listbox4.configure(foreground="#000000")
        self.Listbox4.configure(highlightbackground="#d9d9d9")
        self.Listbox4.configure(highlightcolor="black")
        self.Listbox4.configure(selectbackground="blue")
        self.Listbox4.configure(selectforeground="white")

        self.Label11 = tk.Label(self.top)
        self.Label11.place(relx=0.598, rely=0.577, height=19, width=170)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(anchor='w')
        self.Label11.configure(background="#EEEDDE")
        self.Label11.configure(compound='left')
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Lista Ordenada''')

        self.Label12 = tk.Label(self.top)
        self.Label12.place(relx=0.013, rely=0.709, height=61, width=203)
        self.Label12.configure(anchor='w')
        self.Label12.configure(background="#EEEDDE")
        self.Label12.configure(compound='left')
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
def start_up():
    guiprograma_support.main()

if __name__ == '__main__':
    guiprograma_support.main()




