#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 21, 2022 02:25:33 PM EST  platform: Windows NT


from asyncio.windows_events import NULL
from cProfile import label
from os.path import dirname, join
import itertools
import random
import math
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import time
import guiprograma
import algoritmos
import matplotlib.pyplot as plt
import numpy as np
import sys
from tkinter import messagebox
a=algoritmos.algoritmos()
dic_algoritmos={
        0:'bubblesort',
        1:'bucketsort',
        2:'countingsort',
        3:'heapsort',
        4:'quicksort',
        5:'mergesort',
        6:'insertionsort',
        7:'shellsort',
        8:'stoogesort',
        9:'selectionsort',
        10:'radixsort',
        11:'Todos'
         }
algoritmoss=[a.bubblesort, #0
a.bucketsort,               #1
a.countingsort,             #2
a.heapsort,                 #3
a.quicksort,                #4
a.mergesort,                #5
a.insertionsort,            #6
a.shellsort,                #7
a.stoogesort,               #8
a.selectionsort,            #9
a.radixsort,                #10
"Todos"]                    #11   
titulo=""
dir = dirname(__file__)

        
   
def listaAleatorios(cantidad,digito):
      lista = np.zeros(cantidad)
      for i in range(cantidad):
          lista[i] = random.randint(10**(digito-1), 10**(digito)-1)
      return lista
def leerArreglo(cantidad,digitos,tipo): 
    if(tipo=="numeros"):
        print(cantidad)
        if(digitos>0):
            num=str(digitos)
        else:
            num=""
        num="./numeros"+num+".txt"
        #arreglo=np.genfromtxt(("numeros"+num+".txt"),delimiter=',',dtype=int,skip_footer=cantidad)
        num = join(dir, num)
        arreglo = np.loadtxt(num, delimiter=",", usecols=range(cantidad), dtype=int)               
        return arreglo
    else:
        palabra="./palabras.txt"  
        palabra = join(dir, palabra) 
        aux=[]
        if( digitos!=0):
            print("digito diferente de 0")
            palabra=np.loadtxt(palabra, delimiter="\n", dtype=str, encoding="utf8")            
            for i in range(len(palabra)):
                if(len(palabra[i])==digitos and len(aux)<=cantidad):
                    aux.append(palabra[i])                
            random.shuffle(aux)
            palabra=[]            
            return aux
        else:
            res =np.loadtxt(palabra, delimiter="\n", dtype=str, encoding="utf8", max_rows=cantidad) 
            random.shuffle(res)           
            return res
       


def iniciar(*args):  
    global titulo  
    tipo=args[1] 
    arreglo=[]
    digito=int(args[2])    
    cantidad=int(args[3])
    aux=cantidad       
    tiempo=[]
    salto=int(args[5])
    epocas=int(args[4])
    lista_de_numeros=[]  
    marcador='o'
    arreglo_inicio=[]
    arreglo_fin=[]
    #print(args[0])  
    if(args[0]!=11):
            if(tipo=="letras"):
                if(args[0]==1 or args[0]==2 or args[0]==10):
                    messagebox.showinfo(message="no se puede realizar con letras", title="Título")
                    return
                marcador='^'                
            else:
                marcador='o'
            arreglo=leerArreglo(cantidad,digito,tipo) 
            arreglo_inicio=list(arreglo)
            for j in range(len(arreglo_inicio)):
                 args[8].insert(j,str(j)+".- "+str(arreglo_inicio[j]))
            for i in range(epocas):
                n=len(arreglo)
                lista_de_numeros.append(cantidad)
                if(args[0]==8 or args[0]==4):
                    start = time.time()
                    (algoritmoss[args[0]])(arreglo,0,n-1)               
                    end = time.time()
                    tm=end-start
                    tiempo.append(tm)                    
                else:
                    start = time.time()
                    (algoritmoss[args[0]])(arreglo)               
                    end = time.time()
                    tm=end-start
                    tiempo.append(tm)                
                #print("el tiempo que demoro es")
                args[6].insert(i,str(i)+".-"+str(cantidad)+"-"+tipo+" "+dic_algoritmos[args[0]])
                args[7].insert(i,str(i)+".- "+str(tm))
                arreglo_fin=list(arreglo)    
                #print(tiempo)
                arreglo=[]
                cantidad +=salto 
                           
                arreglo=leerArreglo(cantidad,digito,tipo)
            for j in range(len(arreglo_fin)):
                args[9].insert(j,str(j)+".- "+str(arreglo_fin[j]))
            
            plt.plot(lista_de_numeros,tiempo,marcador,label=tipo+" "+dic_algoritmos[args[0]])
            plt.ylabel("tiempo(s)")
            plt.xlabel("cantidad")         
            plt.legend()
            plt.show()
            tiempo=[]
            lista_de_numeros=[]
            arreglo=[]  
            
    else:
        for j in range(11):
            if(tipo=="letras"):
                if(j==1 or j==2 or j==10 ):
                    continue
                marcador='^'                
            else:
                marcador='o'            
            arreglo=leerArreglo(cantidad,digito,tipo)
            arreglo_inicio=list(arreglo)
            for f in range(len(arreglo_inicio)):
                 args[8].insert(f,str(f)+".- "+str(arreglo_inicio[f]))                             
            for i in range(epocas):
                if(j==8):
                    continue
                else:
                    n=len(arreglo)                                             
                    lista_de_numeros.append(cantidad)                
                    if(j==8 or j==4):
                        start = time.time()
                        (algoritmoss[j])(arreglo,0,n-1)               
                        end = time.time()
                        tm=end-start
                        tiempo.append(end-start)
                        
                    else:
                        start = time.time()
                        (algoritmoss[j])(arreglo)               
                        end = time.time()
                        tm=end-start
                        tiempo.append(end-start)
                        #print(arreglo)
                        #print("el tiempo que demoro es")
                    #print(tiempo)
                    args[6].insert(i,str(i)+".-"+str(cantidad)+"-"+tipo+" "+dic_algoritmos[j])
                    args[7].insert(i,str(i)+".- "+str(tm))
                    arreglo_fin=list(arreglo)   
                    arreglo=[]
                    cantidad +=salto                
                    arreglo=leerArreglo(cantidad,digito,tipo)
                    #print(arreglo)
            for k in range(len(arreglo_fin)):
                args[9].insert(k,str(k)+".- "+str(arreglo_fin[k]))
            cantidad=aux
            plt.plot(lista_de_numeros,tiempo,marcador,label=tipo+" "+dic_algoritmos[j])          
            tiempo=[]
            lista_de_numeros=[]
            arreglo=[]       
        plt.xlabel("cantidad") 
        plt.legend()
        plt.show() 
            
        
        

    



    
            

    

def main(*args):
    sys.setrecursionlimit(60000)
    print(sys.getrecursionlimit())
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = guiprograma.Toplevel1(_top1)
    
    root.mainloop()

if __name__ == '__main__':
    guiprograma.start_up()
def entrada(*args):    
    if(args[1]=="numeros"):
        args[0]['state']=tk.NORMAL       
    else:
        args[0]['state']=tk.NORMAL        
        


